return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 90,
  height = 51,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 23,
  nextobjectid = 544,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "infos",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 484,
          name = "info3",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 828,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "info2",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 800,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "info1",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 772,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "shortcuts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 531,
          name = "QUIT-_SC",
          type = "",
          shape = "text",
          x = 1324,
          y = 16,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "ESC",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 540,
          name = "SEED_SC",
          type = "",
          shape = "text",
          x = 128,
          y = 328,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 6",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 541,
          name = "SEED_SC",
          type = "",
          shape = "text",
          x = 80,
          y = 328,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 4",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 542,
          name = "RANDOM_SEED_SC",
          type = "",
          shape = "text",
          x = 332,
          y = 336,
          width = 36,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 5",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 543,
          name = "EXPORT_SC",
          type = "",
          shape = "text",
          x = 28,
          y = 676,
          width = 96,
          height = 20,
          rotation = 0,
          visible = true,
          text = "NUM ENTER",
          pixelsize = 12,
          wrap = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "resets",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "params",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 520,
          name = "SAVE",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 696,
          width = 84,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 530,
          name = "OPENEND",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 48,
          width = 88,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "NUM_ROW_TEXT",
          type = "",
          shape = "text",
          x = 172,
          y = 168,
          width = 116,
          height = 20,
          rotation = 0,
          visible = true,
          text = "maze rows (odd)",
          wrap = true,
          properties = {}
        },
        {
          id = 524,
          name = "ROW+",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 172,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "ROW-",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 172,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "ROWS",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 172,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "NUM_COL_TEXT",
          type = "",
          shape = "text",
          x = 172,
          y = 124,
          width = 112,
          height = 20,
          rotation = 0,
          visible = true,
          text = "maze cols (odd)",
          wrap = true,
          properties = {}
        },
        {
          id = 179,
          name = "COL+",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "COL-",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "COLS",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 128,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "CELL_H_TEXT",
          type = "",
          shape = "text",
          x = 172,
          y = 264,
          width = 104,
          height = 20,
          rotation = 0,
          visible = true,
          text = "cell height",
          wrap = true,
          properties = {}
        },
        {
          id = 512,
          name = "CELL_H+",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 268,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "CELL_H-",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 268,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "CELL_H",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 268,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "CELL_W_TEXT",
          type = "",
          shape = "text",
          x = 172,
          y = 220,
          width = 96,
          height = 20,
          rotation = 0,
          visible = true,
          text = "cell width",
          wrap = true,
          properties = {}
        },
        {
          id = 419,
          name = "CELL_W+",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "CELL_W-",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "CELL_W",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 224,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 536,
          name = "RANDOM_SEED",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 332,
          width = 60,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "SEED_TEXT",
          type = "",
          shape = "text",
          x = 172,
          y = 340,
          width = 40,
          height = 20,
          rotation = 0,
          visible = true,
          text = "seed",
          wrap = true,
          properties = {}
        },
        {
          id = 534,
          name = "SEED+",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 344,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "SEED-",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 344,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "SEED",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 344,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "menu",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 528,
          name = "RESET_MAZE_POS",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 20,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "COLOR_PICKER",
          type = "",
          shape = "rectangle",
          x = 20,
          y = 12,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "EXIT",
          type = "",
          shape = "rectangle",
          x = 1324,
          y = 32,
          width = 84,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
