return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 90,
  height = 51,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 23,
  nextobjectid = 598,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "infos",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 484,
          name = "info3",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 844,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "info2",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 816,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "info1",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 788,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "shortcuts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 578,
          name = "QUIT-_SC",
          type = "",
          shape = "text",
          x = 1324,
          y = 16,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "ESC",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 566,
          name = "EXPORT_SC",
          type = "",
          shape = "text",
          x = 28,
          y = 696,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM ENTER",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 565,
          name = "RANDOM_SEED_SC",
          type = "",
          shape = "text",
          x = 344,
          y = 352,
          width = 36,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 5",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 567,
          name = "NOISE_SC",
          type = "",
          shape = "text",
          x = 12,
          y = 284,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 7",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 568,
          name = "NOISE_SC",
          type = "",
          shape = "text",
          x = 60,
          y = 284,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 9",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 581,
          name = "SEED_SC",
          type = "",
          shape = "text",
          x = 96,
          y = 344,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 4",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 582,
          name = "SEED_SC",
          type = "",
          shape = "text",
          x = 144,
          y = 344,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 6",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 583,
          name = "NUM_SC",
          type = "",
          shape = "text",
          x = 392,
          y = 688,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM .",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 592,
          name = "NUM2_SC",
          type = "",
          shape = "text",
          x = 264,
          y = 688,
          width = 36,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 2",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 593,
          name = "NUM3_SC",
          type = "",
          shape = "text",
          x = 144,
          y = 632,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 3",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 594,
          name = "NUM1_SC",
          type = "",
          shape = "text",
          x = 100,
          y = 632,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 1",
          pixelsize = 12,
          wrap = true,
          properties = {}
        },
        {
          id = 597,
          name = "NUM_SC",
          type = "",
          shape = "text",
          x = 326,
          y = 708,
          width = 40,
          height = 16,
          rotation = 0,
          visible = true,
          text = "NUM 0",
          pixelsize = 12,
          wrap = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "resets",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 569,
          name = "widthreset",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 96,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 570,
          name = "heightreset",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 140,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 572,
          name = "frequencyreset",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 404,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 573,
          name = "octavesreset",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 448,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 574,
          name = "lacunarityreset",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 492,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 575,
          name = "fractalgainreset",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 592,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 576,
          name = "offsetxreset",
          type = "",
          shape = "rectangle",
          x = 332,
          y = 192,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 577,
          name = "offsetyreset",
          type = "",
          shape = "rectangle",
          x = 332,
          y = 236,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "params",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 520,
          name = "EXPORT",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 712,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 542,
          name = "NOISE_TEXT",
          type = "",
          shape = "text",
          x = 104,
          y = 296,
          width = 60,
          height = 20,
          rotation = 0,
          visible = true,
          text = "noise",
          wrap = true,
          properties = {}
        },
        {
          id = 541,
          name = "NOISE+",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 300,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "NOISE-",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 300,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 539,
          name = "NOISE",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 300,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "HEIGHT_TEXT",
          type = "",
          shape = "text",
          x = 180,
          y = 136,
          width = 48,
          height = 20,
          rotation = 0,
          visible = true,
          text = "height",
          wrap = true,
          properties = {}
        },
        {
          id = 524,
          name = "HEIGHT+",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 140,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "HEIGHT-",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 140,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "HEIGHT",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 140,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "WIDTH_TEXT",
          type = "",
          shape = "text",
          x = 180,
          y = 92,
          width = 48,
          height = 20,
          rotation = 0,
          visible = true,
          text = "width",
          wrap = true,
          properties = {}
        },
        {
          id = 179,
          name = "WIDTH+",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "WIDTH-",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "WIDTH",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 96,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "FREQUENCY_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 400,
          width = 72,
          height = 20,
          rotation = 0,
          visible = true,
          text = "frequency",
          wrap = true,
          properties = {}
        },
        {
          id = 512,
          name = "FREQUENCY+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 404,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "FREQUENCY-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 404,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "FREQUENCY",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 404,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 530,
          name = "RANDOM_SEED",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 348,
          width = 60,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "SEED_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 356,
          width = 40,
          height = 20,
          rotation = 0,
          visible = true,
          text = "seed",
          wrap = true,
          properties = {}
        },
        {
          id = 419,
          name = "SEED+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 360,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "SEED-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 360,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "SEED",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 360,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 534,
          name = "OCTAVES_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 444,
          width = 56,
          height = 20,
          rotation = 0,
          visible = true,
          text = "octaves",
          wrap = true,
          properties = {}
        },
        {
          id = 533,
          name = "OCTAVES+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 448,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "OCTAVES-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 448,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 531,
          name = "OCTAVES",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 448,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 538,
          name = "LACUNARITY_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 488,
          width = 72,
          height = 20,
          rotation = 0,
          visible = true,
          text = "lacunarity",
          wrap = true,
          properties = {}
        },
        {
          id = 537,
          name = "LACUNARITY+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 492,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 536,
          name = "LACUNARITY-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 492,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "LACUNARITY",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 492,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "INTERP_TEXT",
          type = "",
          shape = "text",
          x = 104,
          y = 540,
          width = 96,
          height = 20,
          rotation = 0,
          visible = true,
          text = "interp",
          wrap = true,
          properties = {}
        },
        {
          id = 544,
          name = "INTERP+",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 543,
          name = "INTERP-",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 544,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "INTERP",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 544,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "FRACTALGAIN_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 588,
          width = 80,
          height = 20,
          rotation = 0,
          visible = true,
          text = "fractal gain",
          wrap = true,
          properties = {}
        },
        {
          id = 549,
          name = "FRACTALGAIN+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 592,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "FRACTALGAIN-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 592,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "FRACTALGAIN",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 592,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 558,
          name = "OFFSETX_TEXT",
          type = "",
          shape = "text",
          x = 180,
          y = 188,
          width = 56,
          height = 20,
          rotation = 0,
          visible = true,
          text = "offset x",
          wrap = true,
          properties = {}
        },
        {
          id = 557,
          name = "OFFSETX+",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 556,
          name = "OFFSETX-",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 555,
          name = "OFFSETX",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 192,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "OFFSETY_TEXT",
          type = "",
          shape = "text",
          x = 180,
          y = 232,
          width = 104,
          height = 20,
          rotation = 0,
          visible = true,
          text = "offset y",
          wrap = true,
          properties = {}
        },
        {
          id = 561,
          name = "OFFSETY+",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 236,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 560,
          name = "OFFSETY-",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 236,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 559,
          name = "OFFSETY",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 236,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 580,
          name = "SCALEY",
          type = "",
          shape = "rectangle",
          x = 348,
          y = 136,
          width = 28,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 579,
          name = "SCALEX",
          type = "",
          shape = "rectangle",
          x = 348,
          y = 92,
          width = 28,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 591,
          name = "RANDOM_COLORSEED",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 636,
          width = 60,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 590,
          name = "COLORSEED_TEXT",
          type = "",
          shape = "text",
          x = 188,
          y = 644,
          width = 40,
          height = 20,
          rotation = 0,
          visible = true,
          text = "seed",
          wrap = true,
          properties = {}
        },
        {
          id = 589,
          name = "COLORSEED+",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 648,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 588,
          name = "COLORSEED-",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 648,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 587,
          name = "COLORSEED",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 648,
          width = 56,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 596,
          name = "COLORCOUNT",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 640,
          width = 28,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "menu",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 529,
          name = "EXIT",
          type = "",
          shape = "rectangle",
          x = 1324,
          y = 32,
          width = 84,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "RESET_POS",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 20,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "COLOR_PICKER",
          type = "",
          shape = "rectangle",
          x = 20,
          y = 12,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
